name: ecommerce_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.1.4
  google_sign_in: ^5.0.4
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  flutter_facebook_login: ^3.0.0
  cloud_firestore: "^2.2.1"
  sqflite: ^1.3.0
  path: ^1.8.0
  shared_preferences: ^2.0.6
  flutter_svg: ^0.22.0
  status_change: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/menu_icon/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
      - asset: assets/fonts/Quicksand-Medium.ttf
